# Generated by Django 5.2 on 2025-04-09 16:27

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название своей привычки",
                        max_length=50,
                        verbose_name="Название привычки",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место, где выполянется действие",
                        max_length=100,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        default="00:00",
                        help_text="Укажите время, когда выполняется действие",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Укажите действие",
                        max_length=100,
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите, если это приятная привычка",
                        null=True,
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodic",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="Укажите, сколько раз в неделю будет выполняться привычка",
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        help_text="Укажите награду за выполнение",
                        max_length=250,
                        verbose_name="Награда",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(seconds=120),
                        help_text="Укажите время выполнение",
                        null=True,
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Признак публичности",
                    ),
                ),
            ],
        ),
    ]
