# Generated by Django 5.1.8 on 2025-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodic",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Укажите, сколько раз в неделю будет выполняться привычка",
                null=True,
                verbose_name="Периодичность",
            ),
        ),
    ]
