# Generated by Django 5.1.8 on 2025-04-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_options_alter_habit_periodic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Укажите награду за выполнение",
                max_length=250,
                null=True,
                verbose_name="Награда",
            ),
        ),
    ]
